language: cpp

os:
  # - linux
  - osx

compiler:
  # - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphicsmagick libmagic; travis_wait 30 brew install wxwidgets; fi
  - pip install pillow

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make