language: cpp

os:
  # - linux
  - osx

compiler:
  - gcc
  - clang

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc; sudo apt-add-repository 'deb http://repos.codelite.org/wx3.1.0/ubuntu/ trusty universe' -qq; sudo apt-get update -qq; fi
  - git submodule update

install:
  # Install packages from Homebrew/Aptitude
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphicsmagick libmagic rtmidi; travis_wait 30 brew install wxwidgets; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libwxbase3.1-0-unofficial libwxbase3.1-dev libwxgtk3.1-0-unofficial libwxgtk3.1-dev wx3.1-headers wx-common libwxgtk-webview3.1-0-unofficial libwxgtk-webview3.1-dev libwxgtk-media3.1-0-unofficial libwxgtk-media3.1-dev libwxbase3.1-0-unofficial-dbg libwxgtk3.1-0-unofficial-dbg libwxgtk-webview3.1-0-unofficial-dbg libwxgtk-media3.1-0-unofficial-dbg wx3.1-i18n wx3.1-examples -qq; sudo apt-get install graphicsmagick libgraphicsmagick-dev libgraphicsmagick++-dev libmagic-dev doxygen librtaudio-dev -qq; sudo apt-get install librtmidi-dev -qq; fi
  # Install GooCore
  - cd submodules/GooCore/C++
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -G "Xcode"; xcodebuild -target GooCore -project GooCore.xcodeproj; xcodebuild -target install -project GooCore.xcodeproj; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; make; make install; fi
  - cd ../../../..
  # Install HOWL
  - cd submodules/HOWL
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -G "Xcode"; xcodebuild -target HOWL -project HOWL.xcodeproj; xcodebuild -target install -project HOWL.xcodeproj; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; make; make install; fi
  - cd ../../..
  # Install LibMidifile
  - cd submodules/midifile
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -G "Xcode"; xcodebuild -target midifile -project midifile.xcodeproj; xcodebuild -target install -project midifile.xcodeproj; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; make; make install; fi
  - cd ../../..

before_script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -G "Xcode"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -target lightpad -project lightpad.xcodeproj; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi

deploy:
  provider: releases
  api_key:
    secure: UVCtecHuapK7L/pIlh6bbeAhNVzs1UU6ITRS+tkr4QObk+/yRwxKATln7IEDnH9mJUDLKD7LSjZ5c9PlUohtaZ8yW+aqNtwNbk6LSsSZSr+TNI1VqqB4YoaoDOOMbKPpf55zFp+F/WwiFXZ/vT6DqDsnFrYl5v1kDgTV8NL8eWSszsmXcH1y1jI+0/mSWDyUaK04PYqNmPfY4gnStJD462tyOYZ1l0VIMhrxq1EHYGGRNR1v0z1ucL05faDy/g1JyJ/9AZ0auT2cWKyAFGeTAuTcvtnsVWckAVAnUFQfVfj9nqxUSJpUlc/Ic8SqYe1pssoZ6iWdN/xa0FgEzoqbooiCSQi1ruazcUHMR+cARaFP2cwD6wUfo0hMwaqFJY2Tfp8Hc/BK7eiToC7SGm7gQBoV3wKg7+g1+/vfiaJyvdJfJ5MIgjYJSVv07aMiAq7Y5vhH0FmQx575AIFYGDeC00tKAEYHCRh9wdLMfdsy3rVDLNsWO7ovgD2vP0Qo1guTkz2FjSQI4pWxqiMw+KuOilA2LYYrqpvdygZGAU7eo9vm5/sfn7cQqCUg2yphzGynARcKRJc+uRdqW/DCYL0UfhH3Ix5pYBLpZ5EiMV5LutqQWvf5fk94wXGZqdzG+EmNVdwaiWKtaPfH+TPaH3E+LQ346NBxW75ozPvapMg9mmk=
  skip_cleanup: true
  file: ''
  on:
    repo: GooborgStudios/lightpad
    tags: true