language: cpp

os:
  # - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository 'deb http://repos.codelite.org/wx3.1.0/ubuntu/ zesty universe' -qq; sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphicsmagick libmagic rtmidi; travis_wait 30 brew install wxwidgets; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libwxbase3.1-0-unofficial libwxbase3.1-dev libwxgtk3.1-0-unofficial libwxgtk3.1-dev wx3.1-headers wx-common libwxgtk-webview3.1-0-unofficial libwxgtk-webview3.1-dev libwxgtk-media3.1-0-unofficial libwxgtk-media3.1-dev libwxbase3.1-0-unofficial-dbg libwxgtk3.1-0-unofficial-dbg libwxgtk-webview3.1-0-unofficial-dbg libwxgtk-media3.1-0-unofficial-dbg wx3.1-i18n wx3.1-examples -qq; sudo apt-get install graphicsmagick libgraphicsmagick-dev lib graphicsmagick++-dev libmagic-dev librtmidi-dev doxygen -qq; fi
  - git submodule update
  - cd submodules/NightwaveCore/C++
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ../../../..
  - cd submodules/HOWL
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ../../..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make