language: cpp

os:
  # - linux
  - osx

compiler:
  # - gcc
  - clang

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

# install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphicsmagick libmagic && brew install wxwidgets --devel; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make