//
// Lightpad - Colors.cpp
// Created by Vinyl Darkscratch, Light Apacha, and WhoovesPON3, ©2017 Nightwave Studios.
// Additional assistance by Eric Busch (Origami1105).
// http://www.nightwave.co/lightpad
//

// !!! Auto-generated by sample_colors.py from graphics/references/rgbcolors1.png and ...2.png, DO NOT MODIFY !!!

// Attempt to load precompiled, if compiler doesn't support then load normal
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
	#include <wx/wx.h>
#endif

#include "Colors.h"
#include "rgb2lab.cpp"

#include <stdio.h>
#include <math.h>

!XXX!

unsigned char get_closest_velocity(wxColor c) {
	int best_match_index = 0;
	int best_match_value = 1024;
	for (int i = 0; i < COLORCOUNT; i++) {
		int d = RGB2LAB(velocitycolors[i].Red(), velocitycolors[i].Green(), velocitycolors[i].Blue(), c.Red(), c.Green(), c.Blue());
		if (d < best_match_value) {
			best_match_index = i;
			best_match_value = d;
		}
		//std::cout << i << " - " << d << std::endl;
	}

	return best_match_index;
};