# -*- coding: utf-8 -*-

# Lightpad - sample_colors.py
# ©2017 Nightwave Studios: Vinyl Darkscratch, Light Apacha, Origami1105, WhoovesPON3.
# Additional support from LaunchpadFun (http://www.launchpadfun.com/en/).
# https://www.nightwave.co/lightpad

from PIL import Image

output = "// !!! Auto-generated by sample_colors.py from graphics/rgbcolors.png !!!\n// !!! MAKE CHANGES TO Colors.cpp.in INSTEAD !!!\n\nwxColor velocitycolors[] = {\n\t"

def do_it(img):
	o = []
	for y in range(36, img.height, 74):
		for x in range(36, img.width, 74):
			o.append("wxColor(%d, %d, %d)" %img.getpixel((x, y)))
	return o

output += ",\n\t".join(
	do_it(Image.open('graphics/rgbcolors.png').convert('RGB'))
) + "\n};\n"

cpp_file = open("src/Colors.cpp", "w")
cpp_tmpl = open("src/Colors.cpp.in", "r")

for line in cpp_tmpl:
	if line.strip() == "!XXX!":
		cpp_file.write(output)
	else:
		cpp_file.write(line)

cpp_file.close()
cpp_tmpl.close()
